### ISSUE TITLE
[Feature idea] Mutltiple PrePersist and PostPersist callbacks

### ISSUE THREAD

**Issue by mhlavac** [tomas-pecserke/YamlFixturesBundle#8]
Hello Tomas,

I hope everything is fine and well!

I have an idea to implement in YamlFixturesBundle, but I want to know your opinion first.

Suggested yaml fixture would look like this, so you would be able to call specific calls on entity `Item`, based on callback. This means adding new callback for `prePersist` and allowing `postPersist` without reference to another fixture.

Real-life usage for me is an entity that is able to instantiate it's siblings, so it's more easy to call addNewValue(5), then to create new fixtures with that value. One thing to keep in mind, this way I will not get references for those values, but I don't really need them in first place.

``` yaml
Entity\Item:
    data:
        item.1:
            name: Cool item
            code: cool_item
            @prePersist: [doSomethingCool, [arg1, arg2]]
            @postPersist: [doSomethingCool, [arg1, arg2]]
```

Additionally we could do multiple callbacks like this

``` yaml
Entity\Item:
    data:
        item.1:
            name: Cool item
            code: cool_item
            @prePersist:
                - [doSomethingCool, [arg1, arg2]]
                - [doSomethingCool, [arg1, arg2]]
            @postPersist:
                - [doSomethingCool, [arg1, arg2]]
                - [@cool_fixture, doSomethingCool, [arg1, arg2]]
```

Let me know what do you think.
