### ISSUE TITLE
Command to automatically generate helper fixture classes

### ISSUE THREAD

**Issue by mhlavac** [tomas-pecserke/YamlFixturesBundle#9]
I have idea for one more feature that is not that hard to implement actually, but I want to know your opinion first.

For each fixture we can generate a Fixture class that will have all fixtures as constants. I know this generates some not required code, but this won't be used in production anyway and can help developers because they can easily refer to fixtures with autocomplete features of IDEs.

example would be:

``` yaml
ACME\TestBundle\Entity\Person:
    data:
        person.1:
            code: john_doe
            name: John Doe

        person.2:
            code: joe_doe
            name: Joe Doe
```

Generated class could look like:

``` php
class PersonFixture
{
    const PERSON_1_CODE = 'john_doe';
    const PERSON_1_NAME = 'John Doe';
    const PERSON_2_CODE = 'joe_doe';
    const PERSON_2_NAME = 'Joe Doe';
}
```

Usage in code would be:

``` php
class MyTest extends \PHPUnit_Framework_TestCase
{
    public function myTest()
    {
        $person = fetchByCode(PersonFixture::PERSON_1_CODE);
        $this->assertEquals(PersonFixture::PERSON_1_NAME, $person->getName());
    }
}
```

Let me know what do you think
